apiVersion: v1
kind: Service
metadata:
  name: python-automation-tools-service
spec:
  selector:
    app: python-automation-tools
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 8080  # Port on which the container is running
  type: ClusterIP  # Change to LoadBalancer if you want to expose it externally
